import Link from 'next/link';
import {
  ArrowRight, BarChart3, Camera, Check, ChevronRight, Package,
  ScanLine, ShieldCheck, Sparkles, Store,
} from 'lucide-react';

const features = [
  { icon: ScanLine, title: 'Deteksi produk otomatis', text: 'Arahkan kamera ke produk. Tokiva mengenali dan menambahkannya ke keranjang tanpa scan barcode manual.', tone: 'bg-emerald-100 text-emerald-700' },
  { icon: Package, title: 'Stok selalu terjaga', text: 'Batas stok otomatis mencegah penjualan melebihi persediaan dan menjaga data toko tetap akurat.', tone: 'bg-blue-100 text-blue-700' },
  { icon: BarChart3, title: 'Laporan lebih jelas', text: 'Pantau omzet, laba, produk terlaris, dan aktivitas toko dari satu dashboard sederhana.', tone: 'bg-amber-100 text-amber-700' },
  { icon: ShieldCheck, title: 'Dibuat untuk berkembang', text: 'Data toko tertata, akses aman, dan panel administrasi siap mendukung operasional yang makin besar.', tone: 'bg-violet-100 text-violet-700' },
];

export function Hero() {
  return <section className="relative overflow-hidden pt-36 pb-20 sm:pt-44 sm:pb-28">
    <div className="pointer-events-none absolute -right-40 -top-32 h-[34rem] w-[34rem] rounded-full bg-emerald-200/40 blur-3xl" />
    <div className="pointer-events-none absolute -left-48 bottom-0 h-96 w-96 rounded-full bg-lime-100/50 blur-3xl" />
    <div className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 sm:px-8 lg:grid-cols-[1.02fr_.98fr] lg:px-10">
      <div>
        <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/70 px-4 py-2 text-xs font-bold text-emerald-800 shadow-sm"><Sparkles className="h-4 w-4" /> POS pintar untuk toko modern</div>
        <h1 className="max-w-3xl text-5xl font-black leading-[1.04] tracking-[-0.055em] text-slate-950 sm:text-6xl lg:text-7xl">Kasir lebih cepat.<br /><span className="text-emerald-700">Toko lebih siap.</span></h1>
        <p className="mt-7 max-w-xl text-lg leading-8 text-slate-600 sm:text-xl">Tokiva membantu toko kelontong mengelola penjualan, stok, dan laporan — dengan identifikasi produk otomatis melalui kamera.</p>
        <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/login" className="group inline-flex items-center justify-center gap-3 rounded-2xl bg-emerald-700 px-6 py-4 text-sm font-black text-white shadow-xl shadow-emerald-700/20 transition hover:-translate-y-0.5 hover:bg-emerald-800">Mulai gunakan Tokiva <ArrowRight className="h-5 w-5 transition group-hover:translate-x-1" /></Link><a href="#cara-kerja" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white/70 px-6 py-4 text-sm font-bold text-slate-700 transition hover:border-emerald-300 hover:text-emerald-700">Lihat cara kerja <ChevronRight className="h-4 w-4" /></a></div>
        <div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-slate-500"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-600" /> Tanpa barcode wajib</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-600" /> Berjalan di browser</span></div>
      </div>
      <div id="demo" className="relative mx-auto w-full max-w-xl lg:ml-auto">
        <div className="absolute -inset-4 rounded-[2.5rem] bg-emerald-700/10 blur-2xl" />
        <div className="relative overflow-hidden rounded-[2rem] border border-white bg-white p-3 shadow-2xl shadow-slate-900/15 sm:p-4">
          <div className="rounded-[1.5rem] bg-slate-950 p-4 sm:p-5"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-emerald-500 text-white"><Store className="h-4 w-4" /></span><span className="font-bold text-white">Tokiva POS</span></div><span className="rounded-full bg-emerald-500/15 px-3 py-1 text-[10px] font-bold text-emerald-300">TOKO AKTIF</span></div><div className="grid grid-cols-3 gap-3"><div className="col-span-2 rounded-2xl bg-white p-4"><div className="mb-4 flex items-center justify-between"><span className="text-xs font-bold text-slate-700">Penjualan hari ini</span><BarChart3 className="h-4 w-4 text-emerald-600" /></div><div className="text-2xl font-black text-slate-950">Rp 2.840.000</div><div className="mt-4 h-16"><div className="flex h-full items-end gap-1.5">{[30,45,38,65,52,76,92,68,84,100].map((h,i)=><span key={i} style={{height:`${h}%`}} className={`flex-1 rounded-t-md ${i===9?'bg-emerald-600':'bg-emerald-100'}`} />)}</div></div></div><div className="rounded-2xl bg-emerald-600 p-4 text-white"><Camera className="mb-6 h-6 w-6" /><div className="text-xs font-semibold text-emerald-100">Deteksi produk</div><div className="mt-2 text-lg font-black">Siap scan</div><div className="mt-5 h-1.5 rounded-full bg-emerald-300"><div className="h-full w-3/4 rounded-full bg-white" /></div></div></div><div className="mt-3 rounded-2xl bg-white p-4"><div className="mb-3 flex justify-between"><span className="text-xs font-bold text-slate-700">Aktivitas terbaru</span><span className="text-[10px] font-bold text-emerald-600">Lihat semua</span></div>{['Indomie Goreng','Kopi Kapal Api','Aqua 600ml'].map((name,i)=><div key={name} className="flex items-center justify-between border-t border-slate-100 py-3 text-xs"><span className="font-semibold text-slate-700">{name}</span><span className="font-bold text-slate-950">{['Rp 36.000','Rp 18.500','Rp 12.000'][i]}</span></div>)}</div></div>
        </div>
      </div>
    </div>
  </section>;
}

export function Stats() { return <section className="border-y border-slate-200/70 bg-white/60"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-8 sm:grid-cols-3 sm:px-8 lg:px-10">{[['~350ms','identifikasi per scan'],['100%','berjalan di browser'],['0','barcode wajib untuk mulai']].map(([big,label])=><div key={label} className="flex items-center gap-4 sm:justify-center"><div className="text-3xl font-black tracking-tight text-emerald-700">{big}</div><div className="max-w-[9rem] text-sm font-bold leading-5 text-slate-600">{label}</div></div>)}</div></section>; }

export function Features() { return <section id="fitur" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-700">Satu aplikasi, lebih banyak kendali</p><h2 className="mt-4 text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">Semua yang toko kamu butuhkan.</h2><p className="mt-5 text-lg leading-8 text-slate-700">Dibuat supaya operasional harian terasa ringan, bukan makin rumit.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2">{features.map(({icon:Icon,title,text,tone})=><article key={title} className="group rounded-3xl border border-slate-200/80 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl hover:shadow-slate-900/5"><div className={`flex h-12 w-12 items-center justify-center rounded-2xl ${tone}`}><Icon className="h-6 w-6" /></div><h3 className="mt-6 text-xl font-black text-slate-950">{title}</h3><p className="mt-3 leading-7 text-slate-700">{text}</p><div className="mt-6 h-1 w-10 rounded-full bg-emerald-600 transition-all group-hover:w-20" /></article>)}</div></section>; }

export function HowItWorks() { return <section id="cara-kerja" className="overflow-hidden bg-slate-950 py-24 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-400">Cara kerja</p><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Dari kamera ke keranjang.</h2><p className="mt-5 text-lg leading-8 text-slate-300">Teknologi bekerja di belakang layar. Kamu fokus melayani pelanggan.</p></div><div className="mt-14 grid gap-6 md:grid-cols-3">{[['01','Arahkan kamera','Tunjukkan produk ke kamera dari halaman kasir.'],['02','Tokiva mengenali','Model computer vision membaca produk langsung di browser.'],['03','Selesai terjual','Produk masuk keranjang. Stok dan laporan ikut terbarui.']].map(([num,title,text],i)=><div key={num} className="relative rounded-3xl border border-white/10 bg-white/[.05] p-7">{i<2&&<div className="absolute right-[-1.5rem] top-14 z-10 hidden text-emerald-500 md:block"><ArrowRight /></div>}<div className="text-5xl font-black text-emerald-500/40">{num}</div><h3 className="mt-8 text-xl font-black">{title}</h3><p className="mt-3 leading-7 text-slate-300">{text}</p></div>)}</div></div></section>; }

export function CTA() { return <section id="kontak" className="px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-emerald-700 px-7 py-12 text-center shadow-2xl shadow-emerald-700/20 sm:px-12 sm:py-16"><div className="pointer-events-none absolute" /><h2 className="text-4xl font-black tracking-tight text-white sm:text-5xl">Siap kelola toko lebih cepat?</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-emerald-100">Mulai dari kasir yang lebih sederhana. Bertumbuh dengan data yang lebih jelas.</p><Link href="/login" className="mt-9 inline-flex items-center gap-3 rounded-2xl bg-white px-6 py-4 text-sm font-black text-emerald-800 transition hover:bg-emerald-50">Masuk ke Tokiva <ArrowRight className="h-5 w-5" /></Link></div></section>; }

export function Footer() { return <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-8 sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-10"><div className="flex items-center gap-2 text-lg font-black text-slate-950"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-emerald-700 text-white"><Store className="h-4 w-4" /></span>Tokiva<span className="text-emerald-700">.</span></div><p className="text-sm text-slate-500">POS pintar untuk toko yang terus tumbuh.</p><p className="text-xs font-semibold text-slate-400">© 2026 Tokiva</p></div></footer>; }

export default function LandingSections() { return null; }
                                                      